#ifndef ADV_IPSO_ID_H
#define ADV_IPSO_ID_H

// LWM2M Object ID
#define	OBJ_ID_IPSO_DIGITAl_INPUT      3200
#define	OBJ_ID_IPSO_DIGITAl_OUTPUT     3201
#define	OBJ_ID_IPSO_ANALOGUE_INPUT     3202
#define	OBJ_ID_IPSO_ANALOGUE_OUPUT     3203
#define	OBJ_ID_IPSO_GENERIC_SENSOR     3300
#define	OBJ_ID_IPSO_LUMINOSITY_SENSOR  3301
#define	OBJ_ID_IPSO_PRESENCE_SENSOR    3302
#define	OBJ_ID_IPSO_TEMPERATURE_SENSOR 3303
#define	OBJ_ID_IPSO_HUMIDITY_SENSOR    3304
#define	OBJ_ID_IPSO_POWER_MEASUREMENT  3305
#define	OBJ_ID_IPSO_ACTUATION          3306
#define	OBJ_ID_IPSO_SET_POINT          3308
#define	OBJ_ID_IPSO_LOAD_CONTROL       3310
#define	OBJ_ID_IPSO_LIGHT_CONTROL      3311
#define	OBJ_ID_IPSO_POWER_CONTROL      3312
#define	OBJ_ID_IPSO_ACCELERO_METER     3313
#define	OBJ_ID_IPSO_MAGNETO_METER      3314
#define	OBJ_ID_IPSO_BARO_METER         3315
 
// LWM2M Resource ID
#define	RES_ID_IPSO_DIGITAl_INPUT_STATE  5500
#define	RES_ID_IPSO_DIGITAl_OUTPUT_STATE 5550
#define	RES_ID_IPSO_MIN_RANGE_VALUE      5603
#define	RES_ID_IPSO_MAX_RANGE_VALUE      5604
#define	RES_ID_IPSO_SENSOR_VALUE         5700
#define	RES_ID_IPSO_SENSOR_UNITS         5701
#define	RES_ID_IPSO_X_VALUE              5702
#define	RES_ID_IPSO_Y_VALUE              5703
#define	RES_ID_IPSO_Z_VALUE              5704
#define	RES_ID_IPSO_COMPASS_DIRECTION    5705
#define	RES_ID_IPSO_ON_OFF               5850
#define	RES_ID_IPSO_SET_POINT_VALUE      5900
 
// Advantech Object ID
#define	OBJ_ID_CO2_METER                 9001
#define	OBJ_ID_CO_METER                  9002
#define	OBJ_ID_ULTRASONIC_METER          9200

#endif // ADV_IPSO_ID_H
